### ISSUE TITLE
where is all quizes in all quizes pls

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/IBMDW#1]

**Comment by dennislamcv1** [comment]
I am rearranging all IBM courses since it's so messy

**Comment by johnfelipe** [comment]
Can u ping me when your complete that steps for view and use?

**Comment by johnfelipe** [comment]
Can u share me your Gmail or your mail inself

**Comment by dennislamcv1** [comment]
not doing it bro, Coursera now tightenen the audit mode

**Comment by dennislamcv1** [comment]
I am updating the quizzes as there are new changes in IBM courses recently. I missed the capstone project
